project:
  type: website
  output-dir: docs

website:
  title: "Yasin Asar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - Publications.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
      #- darkly
      #- brand
    css: styles.css
    toc: true



