---
title: "Publications"
editor: visual
---

## Interests

Statistics, Machine Learning, Data Analysis, Regression Analysis

## Journal Papers

-   C. Tanış and **Y. Asar**. Almost unbiased ridge estimator in Bell regression model theory and application to plastic polywood data, Statistics, 58:5, 1031–1045 (2024). <https://doi.org/10.1080/02331888.2024.2389416>.

-   C. Tanış and **Y. Asar**. Liu Type Estimator in Conway-Maxwell-Poisson Regression Model: Theory and Application, Statistics, 58:1, 65–86 (2024). <https://doi.org/10.1080/02331888.2023.2301326>.

-   **Y. Asar**. Performance of a new bias corrected estimator in beta regression model: a Monte Carlo study, Necmettin Erbakan University Journal of Science and Engineering, 5:2, 38–49 (2023). <https://doi.org/10.47112/neufmbd.2023.11>

-   R. A. Belaghi, **Y. Asar** and R. Larsson. Improved shrinkage estimators in the beta regression model with application in econometric and educational data, Statistical Papers, 64, 1891–1912 (2023). <https://doi.org/10.1007/s00362-022-01355-3>

-   **Y. Asar** and R. A. Belaghi. Estimation in Weibull Distribution Under Progressively Type–I Hybrid Censored Data, REVSTAT–Statistical Journal, 20:5, 563–586 (2022). <https://doi.org/10.1080/00949655.2021.1924174>

-   **Y. Asar** and R. A. Belaghi. Inference for Two Lomax Populations Under Joint Type-II Censoring, Communications in Statistics – Simulation and Computation, 51:11, 6808–6825 (2022). <https://www.tandfonline.com/eprint/WVD9VNZQDGHAEUZQ7AGX/full?target=10.1080/03610918.2020.1814814>

-   **Y. Asar** and Z. Algamal. A New Two-parameter Estimator for the Gamma Regression Model, Statistics, Optimization & Information Computing, 10, 750–761 (2022). <https://doi.org/10.19139/soic-2310-5070-822>

-   J. Wu and **Y. Asar**. A Two-Parameter Estimator in Linear Measurement Error Model, Statistics, 56:4, 739–754 (2022). <https://doi.org/10.1080/02331888.2022.2098959>

-   B. Yüzbaşı, **Y. Asar** and S. E. Ahmed. Liu-type Shrinkage Estimations in Linear Models, Statistics, 56:2, 396–420 (2022). <https://doi.org/10.1080/02331888.2022.2055030>

-   **Y. Asar** and M. Korkmaz. Almost unbiased Liu-type estimators in gamma regression model, Journal of Computational and Applied Mathematics, 403, 113819 (2022). <https://doi.org/10.1016/j.cam.2021.113819>

-   M. Arashi, **Y. Asar** and B. Yüzbaşı. SLASSO: A Scaled LASSO for Multicollinear Situations, Journal of Statistical Computation and Simulation, 91:15, 3170–3183 (2021). <https://doi.org/10.1080/00949655.2021.1924174>

-   **Y. Asar** and E. Öğütçüoğlu. A New Biased Estimation Method in Tobit Regression: Theory and Application, Journal of Statistical Simulation and Computation, 91:6, 1257–1273 (2021). <http://dx.doi.org/10.1080/00949655.2020.1845699>

-   Y. Li, **Y. Asar** and J. Wu. On the Stochastic Restricted Liu Estimator in Logistic Regression Model, Journal of Statistical Simulation and Computation, 90:15, 2766–2788 (2020). <https://doi.org/10.1080/00949655.2020.1790561>

-   Z. Algamal and **Y. Asar**. Liu-type estimator for the gamma regression model, Communications in Statistics – Simulation and Computation, 49-8, 2035–2048 (2020). <https://doi.org/10.1080/03610918.2018.1510525>

-   **Y. Asar** and K. Kılınç. A Jackknifed Ridge Estimator in Probit Regression Model, Statistics, 54:4, 667–685 (2020). <http://dx.doi.org/10.1080/02331888.2020.1775597>

-   J. Wu and **Y. Asar**. Efficiency of the Principal Component Liu–type Estimator in Logistic Regression Models, REVSTAT-Statisical Journal 18:3, 325–336 (2020). <https://www.ine.pt/revstat/pdf/REVSTAT_v18-n3-6.pdf>

-   **Y. Asar** and J. Wu. An Improved and Efficient Biased Estimation Technique in Logistic Regression Model, Communications in Statistics – Theory and Methods 49:9, 2237–2252 (2020). <https://doi.org/10.1080/03610926.2019.1568494>

-   J. Wu and **Y. Asar**. On the Stochastic Restricted Liu-type Maximum Likelihood Estimator in Logistic Regression Model, Communications Faculty of Sciences University of Ankara Series A1: Mathematics and Statistics 68:1, 643–653 (2019). <http://dergipark.gov.tr/cfsuasmas/issue/36517/456454>

-   B. Yüzbaşı, **Y. Asar**, M. Ş. Şık and A. Demiralp. Improving Estimations in Quantile Regression Model with Autoregressive Errors, Thermal Science 22:1, 97-107 (2018). <https://doi.org/10.2298/TSCI170612275Y>

-   **Y. Asar**. Performance of a New Restricted Biased Estimator in Logistic Regression, Süleyman Demirel University Journal of Natural and Applied Sciences 22:1, 53-59 (2018). <https://dergipark.org.tr/en/pub/sdufenbed/issue/37055/425667>

-   **Y. Asar** and J. Wu. Performance of the almost unbiased ridge-type principal component estimator in logistic regression model, Communications in Statistics – Simulation and Computation 47:10, 2925-2937 (2018). <http://www.tandfonline.com/doi/full/10.1080/03610918.2017.1364384>
               
-   J. Wu, **Y. Asar** and M. Arashi, On the restricted almost unbiased Liu estimator in the Logistic regression model, Communications in Statistics – Theory and Methods 47:18, 4389-4401 (2018). <https://www.tandfonline.com/eprint/fcZTfivvsgncKmmZRatQ/full>

-   **Y. Asar** and A. Genç. A New Two-Parameter Estimator for the Poisson Regression Model, Iranian Journal of Science and Technology, Transactions A: Science 42:2, 793-803 (2018). <https://link.springer.com/article/10.1007/s40995-017-0174-4>

-   J. Wu and **Y. Asar**. A weighted stochastic restricted ridge estimator in partially linear model, Communications in Statistics – Theory and Methods 46:18, 9274-9283 (2017). <http://www.tandfonline.com/doi/abs/10.1080/03610926.2016.1206936>

-   **Y. Asar** and A. Genç. Two-parameter ridge estimator in the binary logistic regression, Communications in Statistics – Simulation and Computation 46:9, 7088-7099 (2017). <http://www.tandfonline.com/doi/abs/10.1080/03610918.2016.1224348>

-   **Y. Asar**, M. Arashi and J. Wu. Restricted ridge estimator in the logistic regression model, Communications in Statistics – Simulation and Computation 46:8, 6538-6544 (2017). <http://www.tandfonline.com/doi/full/10.1080/03610918.2016.1206932>

-   J. Wu and **Y. Asar**. More on the restricted Liu estimator in the logistic regression model, Communications in Statistics – Simulation and Computation 46:5, 3680-3689 (2017). <http://www.tandfonline.com/doi/abs/10.1080/03610918.2015.1100735>

-   **Y. Asar**, M. Erişoğlu and M. Arashi. Developing a restricted two-parameter Liu-type estimator: A comparison of restricted estimators in the binary logistic regression model, Communications in Statistics – Theory and Methods 46:4, 6864-6873 (2017). <http://www.tandfonline.com/doi/full/10.1080/03610926.2015.1137597>

-   **Y. Asar**. Some new methods to solve multicollinearity in logistic regression, Communications in Statistics – Simulation and Computation 46:4, 2576-2586 (2017). <http://www.tandfonline.com/doi/abs/10.1080/03610918.2015.1053925>

-   **Y. Asar** and A. Genç. A note on some new modifications of ridge estimators, Kuwait Journal of Science 44:3, 75-82 (2017). <http://journalskuwait.org/kjs/index.php/KJS/article/view/1110/203>

-   J. Wu and **Y. Asar**. On almost unbiased ridge logistic estimator for the logistic regression model, Hacettepe Journal of Mathematics and Statistics 45:3, 989-998 (2016). <http://www.hjms.hacettepe.edu.tr/uploads/19dda4f9-aefc-4fa8-b47f-571af3467783.pdf>

-   **Y. Asar**. Liu-type logistic estimators with optimal shrinkage parameter, Journal of Modern and Applied Statistical Methods 15:1, 738-751 (2016). <http://digitalcommons.wayne.edu/cgi/viewcontent.cgi?article=1866&context=jmasm>

-   **Y. Asar** and M. Erişoğlu. Influence diagnostics in two-parameter Ridge regression, Journal of Data Science 14, 33-52 (2016). <http://www.jds-online.com/volume-14-number-1-january-2016>

-   **Y. Asar** and A. Genç. New shrinkage parameters for the Liu-type logistic estimators, Communications in Statistics – Simulation and Computation 45:3, 1094-1103 (2016). <http://www.tandfonline.com/doi/full/10.1080/03610918.2014.995815>

-   A. Karaisa, **Y. Asar** and D.T. Tollu. Fine spectra of triangular triple-band matrices on sequence spaces c and lp, (0 < p < 1), Mathematical Communications 21, 65-83 (2016). <http://www.mathos.unios.hr/mc/index.php/mc/article/view/622>

-   A. Karaisa, D.T. Tollu and **Y. Asar**. Stancu type generalization of q-Favard–Szasz operators, Applied Mathematics and Computation 264, 249–257 (2015). <https://doi.org/10.1016/j.amc.2015.04.101>

-   A. Karaibrahimoğlu, **Y. Asar** and A. Genç. Some new modifications of Kibria’s and Dorugade’s methods: An application to Turkish GDP data, Journal of the Association of Arab Universities for Basic and Applied Sciences 20, 89-99 (2016). <http://www.sciencedirect.com/science/article/pii/S1815385214000558>

-   **Y. Asar**, A. Karaibrahimoglu and A. Genç. Modified Ridge Regression Parameters: A Comparative Monte Carlo Study, Hacettepe Journal of Mathematics and Statistics 43:5, 827-841 (2014). <http://www.hjms.hacettepe.edu.tr/uploads/7742744a-b036-456d-8367-1a3eab73e172.pdf>
